version: "3"
services:
  db:
    image: mongo
    environment:

    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "27017:27017"
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    command: npm run dev
